# Generated by Django 5.2.6 on 2025-09-07 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mascotas', '0002_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='mascotas.owner'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='species',
            field=models.CharField(default='Canino', max_length=50),
        ),
    ]
